language: c
compiler: gcc

before_install:
  - sudo add-apt-repository -y 'ppa:zoogie/sdl2-snapshots'
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libsdl2-dev cppcheck

script: ./ci-build.sh

notifications:
  email: false
